name: falconmetrics_flutter_example
description: "Demonstrates how to use the falconmetrics_flutter plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  falconmetrics_flutter:
    path: ../

  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
